version: '3'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    container_name: jenkins
    restart: always
    ports:
      - '48080:8080'
      - '50000:50000'
    volumes:
      - './data:/var/jenkins_home'
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    environment:
      - DOCKER_HOST=tcp://socat:2375
    links:
      - socat
  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    expose:
        - "2375"